spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:staging-db}:${DB_PORT:5432}/codechallenge_db
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}
  jpa:
    show-sql: false
  kafka:
    listener:
      enabled: true

logging:
  level:
    root: INFO
    de.dk.api.codeChallenge: INFO

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when_authorized